### ISSUE TITLE
Please add Cargo.lock to .gitignore

### ISSUE THREAD

**Issue by eduardossampaio** [mohanson/gameboy#17] opened 2019-12-30 19:25 UTC
Cargo.lock is a generated file by cargo, but build fail if your generated Cargo.lock is present.
Suggestion: delete Cargo.lock and add it to .gitignore

**Comment by mohanson** [comment] 2019-12-31 03:01
The development spec I understand is that bin needs check-in `Cargo.lock`, See:

https://github.com/rust-lang/cargo/issues/315#issuecomment-51075730

**Comment by eduardossampaio** [comment] 2019-12-31 11:32
That is correct, but Cargo.lock is a generated file by build at first time. I'm suggesting to ignore it because build fails after I clone the project. The error disapeared after I delete the Cargo.lock file.

<img width="572" alt="after removing cargolock" src="https://user-images.githubusercontent.com/11557845/71620302-0238d300-2ba8-11ea-8816-c4c7c8afa264.png">
<img width="611" alt="error Cargolock after git clone" src="https://user-images.githubusercontent.com/11557845/71620303-0238d300-2ba8-11ea-9e0d-4f5c9d0de9f0.png">

**Comment by eduardossampaio** [comment] 2020-01-02 11:55
DX r😢

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ethanpailes** [comment] 2020-03-22 17:31
@eduardossampaio The typical pattern with cargo files is to check in `Cargo.toml` for libraries and checkin in both `Cargo.toml` and `Cargo.lock` for applications. `Cargo.toml` expresses the constraints you believe to describe the deps that work with the project which is good when you have a unknown number of consumers using your packages with their own dep constraints, while `Cargo.lock` describes a list of actual deps which is good when you want stability. Applications don't have any downstream consumers, so Cargo.lock should be checked in.

If deleting `Cargo.lock` fixed the build for you, your compiler version might be out of date with the project or there could just be a bug in the `Cargo.lock` file that needs to be fixed. Perhaps you could post the diff between the `Cargo.lock` that gets generated after you blow away the old one and the one that is checked in. That might show the issue.

**Comment by namibj** [comment] 2020-05-25 03:34
> That is correct, but Cargo.lock is a generated file by build at first time. I'm suggesting to ignore it because build fails after I clone the project. The error disapeared after I delete the Cargo.lock file.

The problem is, that there is zero guarantee that cargo will be able to generate a working `Cargo.lock` file in the future. This is very pronounced with pre-1.0 crates and git-branch-references, as both aren't claiming any stability via SemVer.

**Comment by yazgoo** [comment] 2020-07-17 12:21
As mentioned by @ethanpailes, Cargo.lock should be kept, I think this issue can be closed (my 2 cts :) )

**Closed as completed** 2020-07-17 12:22 UTC
